apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: app
  newName: gomes025/cicd
  newTag: b88dd798529c232ba26c1ef14feaacb614083cbf
