apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: app
  newName: gomes025/cicd
  newTag: c3e2730180c8227db5f2d7f2dfcc0f20987cccb8
